import type { RegistrationItem, RegistrationStatus } from './types'

export const REGISTRATIONS_DATA: RegistrationItem[] = [
  {
    id: 'reg-1',
    initials: 'AS',
    fullName: 'Anahit Sargsyan',
    email: 'anahit@email.am',
    category: 'MUSIC',
    eventName: 'Yerevan Jazz Fest',
    dayMonth: 'Oct 24,',
    year: '2026',
    date: '2026-10-24',
    status: 'Active',
  },
  {
    id: 'reg-2',
    initials: 'GA',
    fullName: 'Gevorg Abrahamyan',
    email: 'gev.ab@mail.ru',
    category: 'TECH',
    eventName: 'Armenia IT Forum',
    dayMonth: 'Oct 26,',
    year: '2026',
    date: '2026-10-26',
    status: 'Pending',
  },
  {
    id: 'reg-3',
    initials: 'NM',
    fullName: 'Nare Mkrtchyan',
    email: 'nare@web.am',
    category: 'ARTS',
    eventName: 'Cascade Wine Days',
    dayMonth: 'Oct 22,',
    year: '2026',
    date: '2026-10-22',
    status: 'Cancelled',
  },
  {
    id: 'reg-4',
    initials: 'AM',
    fullName: 'Artur Melikyan',
    email: 'artur.m@haypost.am',
    category: 'MUSIC',
    eventName: 'Yerevan Jazz Fest',
    dayMonth: 'Oct 24,',
    year: '2026',
    date: '2026-10-24',
    status: 'Active',
  },
  {
    id: 'reg-5',
    initials: 'LP',
    fullName: 'Lilit Petrosyan',
    email: 'lilit.p@ucom.am',
    category: 'TECH',
    eventName: 'Armenia IT Forum',
    dayMonth: 'Oct 26,',
    year: '2026',
    date: '2026-10-26',
    status: 'Active',
  },
  {
    id: 'reg-6',
    initials: 'HH',
    fullName: 'Hayk Hovhannisyan',
    email: 'hayk.h@mail.am',
    category: 'ARTS',
    eventName: 'Cascade Wine Days',
    dayMonth: 'Oct 22,',
    year: '2026',
    date: '2026-10-22',
    status: 'Pending',
  },
  {
    id: 'reg-7',
    initials: 'AG',
    fullName: 'Ani Grigoryan',
    email: 'ani.g@internet.am',
    category: 'MUSIC',
    eventName: 'Yerevan Jazz Fest',
    dayMonth: 'Oct 24,',
    year: '2026',
    date: '2026-10-24',
    status: 'Active',
  },
  {
    id: 'reg-8',
    initials: 'VH',
    fullName: 'Vardan Hakobyan',
    email: 'vardan@arminco.com',
    category: 'TECH',
    eventName: 'Armenia IT Forum',
    dayMonth: 'Oct 26,',
    year: '2026',
    date: '2026-10-26',
    status: 'Cancelled',
  },
  {
    id: 'reg-9',
    initials: 'MA',
    fullName: 'Mariam Asatryan',
    email: 'mariam.a@yahoo.com',
    category: 'ARTS',
    eventName: 'Cascade Wine Days',
    dayMonth: 'Oct 22,',
    year: '2026',
    date: '2026-10-22',
    status: 'Active',
  },
  {
    id: 'reg-10',
    initials: 'TG',
    fullName: 'Tigran Galstyan',
    email: 'tigran.g@gmail.com',
    category: 'MUSIC',
    eventName: 'Yerevan Jazz Fest',
    dayMonth: 'Oct 24,',
    year: '2026',
    date: '2026-10-24',
    status: 'Pending',
  },
  {
    id: 'reg-11',
    initials: 'SK',
    fullName: 'Sona Karapetyan',
    email: 'sona.k@email.am',
    category: 'TECH',
    eventName: 'Armenia IT Forum',
    dayMonth: 'Oct 26,',
    year: '2026',
    date: '2026-10-26',
    status: 'Active',
  },
  {
    id: 'reg-12',
    initials: 'RS',
    fullName: 'Ruben Stepanyan',
    email: 'ruben.s@haypost.am',
    category: 'ARTS',
    eventName: 'Cascade Wine Days',
    dayMonth: 'Oct 22,',
    year: '2026',
    date: '2026-10-22',
    status: 'Active',
  },
  {
    id: 'reg-13',
    initials: 'KO',
    fullName: 'Kristine Ohanyan',
    email: 'kristine@web.am',
    category: 'MUSIC',
    eventName: 'Yerevan Jazz Fest',
    dayMonth: 'Oct 24,',
    year: '2026',
    date: '2026-10-24',
    status: 'Cancelled',
  },
  {
    id: 'reg-14',
    initials: 'AP',
    fullName: 'Aram Poghosyan',
    email: 'aram.p@ucom.am',
    category: 'TECH',
    eventName: 'Armenia IT Forum',
    dayMonth: 'Oct 26,',
    year: '2026',
    date: '2026-10-26',
    status: 'Pending',
  },
  {
    id: 'reg-15',
    initials: 'EM',
    fullName: 'Elina Martirosyan',
    email: 'elina.m@mail.ru',
    category: 'ARTS',
    eventName: 'Cascade Wine Days',
    dayMonth: 'Oct 22,',
    year: '2026',
    date: '2026-10-22',
    status: 'Active',
  },
  {
    id: 'reg-16',
    initials: 'DG',
    fullName: 'David Ghazaryan',
    email: 'david.g@arminco.com',
    category: 'MUSIC',
    eventName: 'Yerevan Jazz Fest',
    dayMonth: 'Oct 24,',
    year: '2026',
    date: '2026-10-24',
    status: 'Active',
  },
  {
    id: 'reg-17',
    initials: 'NS',
    fullName: 'Narine Simonyan',
    email: 'narine.s@internet.am',
    category: 'TECH',
    eventName: 'Armenia IT Forum',
    dayMonth: 'Oct 26,',
    year: '2026',
    date: '2026-10-26',
    status: 'Active',
  },
  {
    id: 'reg-18',
    initials: 'AA',
    fullName: 'Armen Avetisyan',
    email: 'armen.a@yahoo.com',
    category: 'ARTS',
    eventName: 'Cascade Wine Days',
    dayMonth: 'Oct 22,',
    year: '2026',
    date: '2026-10-22',
    status: 'Cancelled',
  },
  {
    id: 'reg-19',
    initials: 'GY',
    fullName: 'Gohar Yeghiazaryan',
    email: 'gohar.y@gmail.com',
    category: 'MUSIC',
    eventName: 'Yerevan Jazz Fest',
    dayMonth: 'Oct 24,',
    year: '2026',
    date: '2026-10-24',
    status: 'Pending',
  },
  {
    id: 'reg-20',
    initials: 'RD',
    fullName: 'Raffi Danielyan',
    email: 'raffi.d@email.am',
    category: 'TECH',
    eventName: 'Armenia IT Forum',
    dayMonth: 'Oct 26,',
    year: '2026',
    date: '2026-10-26',
    status: 'Active',
  },
  {
    id: 'reg-21',
    initials: 'TM',
    fullName: 'Tamar Muradyan',
    email: 'tamar.m@haypost.am',
    category: 'ARTS',
    eventName: 'Cascade Wine Days',
    dayMonth: 'Oct 22,',
    year: '2026',
    date: '2026-10-22',
    status: 'Active',
  },
  {
    id: 'reg-22',
    initials: 'VN',
    fullName: 'Vahe Nazaryan',
    email: 'vahe.n@web.am',
    category: 'MUSIC',
    eventName: 'Yerevan Jazz Fest',
    dayMonth: 'Oct 24,',
    year: '2026',
    date: '2026-10-24',
    status: 'Pending',
  },
  {
    id: 'reg-23',
    initials: 'LM',
    fullName: 'Lusine Manukyan',
    email: 'lusine.m@ucom.am',
    category: 'TECH',
    eventName: 'Armenia IT Forum',
    dayMonth: 'Oct 26,',
    year: '2026',
    date: '2026-10-26',
    status: 'Cancelled',
  },
  {
    id: 'reg-24',
    initials: 'GS',
    fullName: 'Gagik Sargsyan',
    email: 'gagik.s@mail.am',
    category: 'ARTS',
    eventName: 'Cascade Wine Days',
    dayMonth: 'Oct 22,',
    year: '2026',
    date: '2026-10-22',
    status: 'Active',
  },
  {
    id: 'reg-25',
    initials: 'MM',
    fullName: 'Mane Mirzoyan',
    email: 'mane.m@arminco.com',
    category: 'MUSIC',
    eventName: 'Yerevan Jazz Fest',
    dayMonth: 'Oct 24,',
    year: '2026',
    date: '2026-10-24',
    status: 'Active',
  },
  {
    id: 'reg-26',
    initials: 'HB',
    fullName: 'Hrach Baghdasaryan',
    email: 'hrach.b@internet.am',
    category: 'TECH',
    eventName: 'Armenia IT Forum',
    dayMonth: 'Oct 26,',
    year: '2026',
    date: '2026-10-26',
    status: 'Pending',
  },
]

export const STATUS_CLASS_BY_VALUE: Record<RegistrationStatus, string> = {
  Active: 'statusActive',
  Pending: 'statusPending',
  Cancelled: 'statusCancelled',
}

export const PAGE_SIZE = 20
